version: '2'
services:
  utility-discord-bot:
    build: .
    restart: unless-stopped
    container_name: utility-discord-bot
    tty: true
    command: npm run dev
    volumes:
      - .:/code/
      - /code/node_modules
    ports:
      - 3000:3000
    depends_on:
      - utility-discord-bot-db
  utility-discord-bot-db:
    container_name: utility-discord-bot-db
    volumes:
      - utility-discord-bot-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    image: postgres:11.5
    environment:
      POSTGRES_DB: utility-discord-bot-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
volumes:
  utility-discord-bot-db-data: {}
