version: '2'
services:
  utility-discord-bot:
    build: .
    restart: unless-stopped
    container_name: utility-discord-bot
    tty: true
    command: npm run dev
    volumes:
      - .:/code/
      - /code/node_modules
    ports:
      - 3000:3000
    depends_on:
      - utility-discord-bot-db
  utility-discord-bot-db:
    container_name: utility-discord-bot-db
    volumes:
      - utility-discord-bot-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    image: postgres:11.5
    environment:
      POSTGRES_DB: utility-discord-bot-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  # Note: hot reloading doesn't work in CRA 5
  # https://github.com/facebook/create-react-app/issues/11879
  # utility-discord-bot-website:
  #   build: ../Utility-Discord-Bot-Website
  #   env_file:
  #     - ../Utility-Discord-Bot-Website/.env
  #   environment:
  #     PORT: 8080
  #   restart: always
  #   container_name: utility-discord-bot-website
  #   command: npm start
  #   volumes:
  #     - ../Utility-Discord-Bot-Website:/code/
  #     - /code/node_modules
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - utility-discord-bot
volumes:
  utility-discord-bot-db-data: {}
